djangoProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('',views.index, name='index'),
    path('add',views.add, name='add'),
    path('add/<int:exam_id>/problem',views.problem, name='problem'),
    path('<int:exam_id>/', views.detail, name='detail'),
     path('<int:exam_id>/statistic', views.statistic, name='statistic'),
    path('<int:exam_id>/results/', views.results, name='results'),
    path('<int:exam_id>/score/', views.score, name='score'),
    path('add/<int:exam_id>/problem/addProblem', views.addProblem, name='addProblem'),
]

polls/models.py
from django.db import models

# Create your models here.

class Exam(models.Model):
    exam_text = models.CharField(max_length=200)

    def __str__(self):
        return self.exam_text

class Question(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question_text = models.TextField()
    question_contents = models.TextField()

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    answer = models.BooleanField(default = False)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import  Choice,Question,Exam
from django.http import Http404


def index(request):
    latest_exam_list = Exam.objects.order_by()
    return render(request,'polls/index.html', {'latest_exam_list': latest_exam_list})

def statistic(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)
    static_list = []

    for question in exam.question_set.all():
        users = 0
        answer_num = 0
        for choice in question.choice_set.all():
            users += choice.votes
            if choice.answer == True:
                answer_num += choice.votes
        if(users == 0):
            users = 1
        
        static_list.append(round(answer_num/users*100, 2))
    return render(request,'polls/statistic.html',{'exam':exam, 'static_list': static_list})

def problem(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)
    return render(request,'polls/problem.html',{'exam':exam})

def addProblem(request, exam_id):
    try:
        Exam.objects.create(
            exam_text = request.POST['ename']
        )
        return HttpResponseRedirect(reverse('polls:add'))
    except:
        exam_now = get_object_or_404(Exam, pk= exam_id)
        if 'on' in request.POST.getlist('choice', ''):
            Question.objects.create(
                question_text = request.POST['qname'],
                question_contents = request.POST['qcontents'],
                exam = exam_now
            )
            condition = False
            for i in request.POST.getlist('choice', ''):
                if i == 'on':
                    condition = True
                else:
                    Choice.objects.create(
                        choice_text = i,
                        answer = condition,
                        votes = 0,
                        question = Question.objects.order_by('-pk')[0]
                    )
                    condition = False
        else:
            return render(request, 'polls/problem.html',{'exam':exam_now,'error_message':'Fail to save Problem. There must be at least one answer'})
    else:
        pass
    return HttpResponseRedirect(reverse('polls:index'))

def add(request):
    latest_exam_list = Exam.objects.order_by()
    return render(request,'polls/add.html',{'latest_exam_list': latest_exam_list})

def detail(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)

    return render(request, 'polls/detail.html',{'exam':exam})

def results(request, exam_id, score):
    exam = get_object_or_404(Exam, pk= exam_id)

    return render(request, 'polls/results.html',{'exam':exam ,'score':score})


def score(request, exam_id):
    exam = get_object_or_404(Exam, pk= exam_id)
    selected_choices = []
    score = 0
    num = 0
    try:
        for question in exam.question_set.all():
            selected_choices.append(question.choice_set.get(pk=request.POST[question.question_text])) 
            num += 1
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'exam': exam,'error_message': "You didn't select a choice.",})
    else:
        for i in selected_choices:
            i.votes += 1
            i.save()
            if i.answer == True:
                score += 100/num
        return render(request,'polls/results.html',{'exam': exam, 'score':round(score,2)} )

polls/templates/polls/add.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Exam & Problem</title>
    <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>



<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>Make Exam or Problem Page</h1>
        </div>
        <div id="jb-maincontent">
            <h2>Click Exam to make Problem</h2>
            {% if latest_exam_list %}
            <ul>
                {%  for exam in latest_exam_list %}
                    <li><a href="{% url 'polls:problem' exam.id %}">{{  exam.exam_text }}</a></li>
                {%  endfor  %}
            </ul>
            {% else %}
                <p>No exam are available.</p>
            {% endif %}
        </div>
        

        <div id="jb-sidebar">
            <a href="{% url 'polls:index'%}">Main Page</a>
        </div>
        <div id="jb-content">
            <h2>Make Exam</h2>
            <form action="{%  url 'polls:addProblem' 0 %}" method="post">
                {% csrf_token %}
                <p>Exam name <input type='text' name='ename' ><input type="submit" value="Submit"><br></p>
            </form>
        </div>
        
        

        <div id="jb-footer">
            <p>django exam project made bj CJH</p>
        </div>
        
        
    </div>
</body>

polls/templates/polls/detail.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Take Exam</title>
    <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>

<body>

<div id="jb-container">
    <div id="jb-header">
        <h1>{{ exam.exam_text }}</h1>
        {% if error_message %}<p style="color:#FF0000"><strong>{{  error_message }}</strong></p>{% endif %}
    </div>
    
    <form action="{%  url 'polls:score' exam.id %}" method="post">
        {% csrf_token %}

        {% for question in exam.question_set.all %}
            <div id="jb-maincontent">
                <h3>{{ question.question_text|linebreaks }}</h3>
                <h5>{{ question.question_contents|linebreaks }}</h5>
                <h3>___________________________</h3>

                {% for choice in question.choice_set.all %}
                    <input type="radio" name="{{question.question_text}}" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>

                {% endfor %}
            </div>
        {% endfor %}
        <div id="jb-maincontent">
            <p><strong>Notice!!!
                if you finish the exam, click "Submit" Button</strong></p>
        </div>
        <div id="jb-content">
            <input type="submit" value="Submit"><br><br>
            <a href="{% url 'polls:index'%}">Main page</a>
        </div>
        <div id="jb-footer">
            <p>django exam project made bj CJH</p>
        </div>
    
    </form>

    
    

</div>

</body>

polls/templates/polls/index.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Exam Sharing HUB</title>
    <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>

<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>Exam sharing HUB</h1>
        </div>
        <div id="jb-content">
            <p>Hello! This page is example of django project.</p>
        </div>
        {% if latest_exam_list %}
            <div id="jb-sidebar">
            <h4>
                exam list
            </h4>
                {%  for exam in latest_exam_list %}
        
                    {{ exam.exam_text }}<br>
                    - <a href="{% url 'polls:detail' exam.id %}">Take exam</a><br>
                    - <a href="{% url 'polls:statistic' exam.id %}">statistic</a><br><br>
                {%  endfor  %}
            </div>
        {% else %}
            <div id="jb-sidebar">
                <p>No Exam are available.</p>
            </div>
            
        {% endif %}
            
        <div id="jb-maincontent">
            <a href="{% url 'polls:add'%}">Add Exam & Problem</a>
        </div>

        <div id="jb-footer">
            django exam project made bj CJH
        </div>

        
    </div>





    


</body>

polls/templates/polls/problem.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Problem</title>
    <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>

<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>Make Problem</h1>
            {% if error_message %}<p style="color:#FF0000"><strong>{{  error_message }}</strong></p>{% endif %}
        </div>
        <div id="jb-maincontent">
            <form action="{%  url 'polls:addProblem' exam.id %}" method="post">
                {% csrf_token %}
                <p>Problem name <br><textarea id='qname' name='qname' rows='1' cols='40'></textarea></p>
                <p>Problem contents <br><textarea id='qcontents' name='qcontents' rows='3' cols='40'></textarea></p>
                <div id="t_space">
                <p>add choice <input type="button" value="add" onclick='add_textbox()'><br></p> 
                
                </div>
        
                <input type="submit" value="Submit"><br>
                <a href="{% url 'polls:index'%}">Main Page</a>
            </form>
        </div>

        <div id="jb-footer">
            <p>django exam project made bj CJH</p>
        </div>
        
    
        <script>
            function add_textbox(){
                document.getElementById("t_space").innerHTML +=
                "isAnswer? <input type='radio' name='choice' >Choice name <input type='text' name='choice' > <br>";
            }
        </script>
    </div>

    

</body>

polls/templates/polls/results.html
<!DOCTYPE html>

<html lang="en">

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Result</title>
       <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>

<body>

<div id="jb-container">
       <div id="jb-header">
              <h1>Exam result</h1>
       </div>
       
       <div id="jb-maincontent">
              <h2>{{ score }}</h2>
              <p><a href="{% url 'polls:detail' exam.id %}">Exam again?</a></p>
       </div>
              
       <div id="jb-maincontent">
              <a href="{% url 'polls:index'%}">Main Page</a>
       </div>

       <div id="jb-footer">
              django exam project made bj CJH
       </div>





</div>



</body>

polls/templates/polls/statistic.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Exam Statistic</title>
    <style>
      #jb-container {
        margin: 10px auto;
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-header {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-content {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-maincontent {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-sidebar {
        padding: 20px;
        margin-bottom: 20px;
        border: 1px solid #bcbcbc;
      }
      #jb-footer {
        padding: 20px;
        border: 1px solid #bcbcbc;
      }
      @media ( min-width: 481px ) {
        #jb-container {
          width: 940px;
        }
        #jb-content {
          width: 580px;
          float: left;
        }
        #jb-maincontent {
          width: 580px;
          float: left;
        }
        #jb-sidebar {
          width: 260px;
          float: right;
        }
        #jb-footer {
          clear: both;
        }
      }
</style>
</head>

<body>
    <div id="jb-container">
        <div id="jb-header">
            <h1>{{"Statistic of "}} {{ exam.exam_text }} </h1>
        </div>
        

        {% load index %}
        
        {% for question in exam.question_set.all %}   
        
            <div id="jb-maincontent">
                <h3> {{'Question : '}}{{ question.question_text |linebreaks}}</h3>
                <h5>{{ question.question_contents|linebreaks }}</h5>
                <h3>___________________________</h3>
                {% for choice in question.choice_set.all %}
                    <li>{{'choice '}}{{choice.choice_text}} -- {{choice.votes}}
                        {% if choice.answer%}
                            {{"<- answer"}}
                        {% else %}
                            
                        {% endif %}
                    </li>
                {% endfor %}

                correct rate <strong>{{static_list|index:forloop.counter0}} %</strong>  <br>
            </div>
        {% endfor %}  

        <div id="jb-maincontent">
            <a href="{% url 'polls:index'%}">Main Page</a>
        </div>

        <div id="jb-footer">
            django exam project made bj CJH
        </div>
    </div>

    
</body>